version: '3'
services:
  flask_ml_app:
    container_name: flask_ml_app
    image: flask_ml_app_img
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mnt/app
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5005:5000"
    